### ISSUE TITLE
Argon2 Support

### ISSUE THREAD

**Issue by NAThompson** [inejge/pwhash#10]
Is implementation of Argon2 on the roadmap for this repo?

**Comment by inejge** [comment]
Not presently, since I'm satisfied to limit the scope of the library to the set of algorithms used by common Unixish `crypt(3)` implementations. Newer hashes (scrypt, PBKDF2, Argon2) haven't been assigned distinct algorithm numbers which they'd need to conform to `crypt(3)` conventions, nor do they have agreed-upon parameter representation for salt strings. Your best bet is to use a dedicated hashing crate such as [argon2rs](https://crates.io/crates/argon2rs).

**Comment by NAThompson** [comment]
Cool, thanks!
